name: btoz
description: "BTOZ Academy - Educational Management System"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  # Core Flutter dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management & Data Persistence
  # Hive is a lightweight and fast key-value database for Flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Shared Preferences for simple key-value storage
  shared_preferences: ^2.2.2
  
  # UUID generation for unique identifiers
  uuid: ^4.5.1

  # UI & Design Dependencies
  # Material Design components and theming
  material_design_icons_flutter: ^7.0.7296
  
  # Charts and data visualization
  fl_chart: ^0.69.0
  
  # Date and time pickers
  intl: ^0.19.0
  
  # Image handling and caching
  cached_network_image: ^3.3.1
  
  # Form validation
  form_validator: ^2.1.1
  
  # Loading animations
  flutter_spinkit: ^5.2.0
  
  # Toast notifications
  fluttertoast: ^8.2.4
  
  # Permission handling
  permission_handler: ^11.3.1
  
  # File picker for document uploads
  file_picker: ^8.0.0+1
  
  # PDF generation and handling
  pdf: ^3.10.7
  path_provider: ^2.1.2
  
  # QR code generation
  qr_flutter: ^4.1.0
  
  # Barcode scanning
  mobile_scanner: ^3.5.6
  
  # Local notifications
  flutter_local_notifications: ^17.2.2
  
  # HTTP requests and API calls
  http: ^1.2.0
  dio: ^5.4.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
 # URL launcher for external links
  url_launcher: ^6.2.4
  
  # Connectivity checking
  connectivity_plus: ^5.0.2
  
  # Device info
  device_info_plus: ^9.1.2
  
  # Secure storage for sensitive data
  flutter_secure_storage: ^9.0.0
  
  # Biometric authentication
  local_auth: ^2.1.8
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # Firebase services (optional for cloud features)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Provider for state management
  provider: ^6.1.2

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  
  # Code generation tools
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  
  # App icon generation
  flutter_launcher_icons: ^0.13.1
  
  # Code coverage
  coverage: ^1.6.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_icon.svg
    - assets/images/app_icon.png
    - assets/images/GoogleG.png
    # Add more asset directories as needed
    # - assets/fonts/
    # - assets/data/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#007AFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
